USE `bd2-23L-z09`;

DROP TABLE IF EXISTS KLIENCI;
DROP TABLE IF EXISTS TYPY_KONTA;
DROP TABLE IF EXISTS KONTA;
DROP TABLE IF EXISTS PRZYNALEZNOSCI_KONT;
DROP TABLE IF EXISTS KARTY;
DROP TABLE IF EXISTS POZYCZKI;
DROP TABLE IF EXISTS SALDA;
DROP TABLE IF EXISTS WALUTY;
DROP TABLE IF EXISTS LOKATY;
DROP TABLE IF EXISTS TRANSAKCJE;
DROP TABLE IF EXISTS KONTA_ZEWNETRZNE;
DROP TABLE IF EXISTS BANKI;
